import 'data_model.dart';

Map<String, List<Tag>> defaultTags = {
  'en': [
    Tag.newTag('winter', "season"),
    Tag.newTag('spring', "season"),
    Tag.newTag('summer', "season"),
    Tag.newTag('autumn', "season"),
    Tag.newTag('vegetarian', "diet"),
    Tag.newTag('vegan', "diet"),
    Tag.newTag('sans gluten', "diet"),
    Tag.newTag('viande', "protein"),
    Tag.newTag('poisson', "protein"),
    Tag.newTag('four', "kitchenware"),
    Tag.newTag('poêle', "kitchenware"),
    Tag.newTag('cocotte-minute', "kitchenware"),
    Tag.newTag('pied à soupe', "kitchenware"),
    Tag.newTag('robot patissier', "kitchenware"),
    Tag.newTag('piquant', ""),
    Tag.newTag('froid', "temperature"),
    Tag.newTag('petit-déjeuner', "meal"),
    Tag.newTag('apéro', "meal"),
    Tag.newTag('déjeuner', "meal"),
    Tag.newTag('dîner', "meal"),
    Tag.newTag('français', "cuisine"),
    Tag.newTag('italien', "cuisine"),
    Tag.newTag('asiatique', "cuisine"),
    Tag.newTag('africain', "cuisine")
  ],
  'fr': [
    Tag.newTag('hiver', "saison"),
    Tag.newTag('printemps', "saison"),
    Tag.newTag('été', "saison"),
    Tag.newTag('automne', "saison"),
    Tag.newTag('végétarien', "régime"),
    Tag.newTag('vegan', "régime"),
    Tag.newTag('sans gluten', "régime"),
    Tag.newTag('viande', "protéine"),
    Tag.newTag('poisson', "protéine"),
    Tag.newTag('four', "matériel"),
    Tag.newTag('poêle', "matériel"),
    Tag.newTag('cocotte-minute', "matériel"),
    Tag.newTag('pied à soupe', "matériel"),
    Tag.newTag('robot patissier', "matériel"),
    Tag.newTag('piquant', ""),
    Tag.newTag('froid', "température"),
    Tag.newTag('petit-déjeuner', "repas"),
    Tag.newTag('apéro', "repas"),
    Tag.newTag('déjeuner', "repas"),
    Tag.newTag('dîner', "repas"),
    Tag.newTag('français', "cuisine"),
    Tag.newTag('italien', "cuisine"),
    Tag.newTag('asiatique', "cuisine"),
    Tag.newTag('africain', "cuisine")
  ]
};


Map<String, List<BookIngredient>> defaultIngredients = {
  'en': [
    BookIngredient.newBookIngredient(name: 'prime rib'),
    BookIngredient.newBookIngredient(name: 'rib steak'),
    BookIngredient.newBookIngredient(name: 'veal rib'),
    BookIngredient.newBookIngredient(name: 'beefsteak'),
    BookIngredient.newBookIngredient(name: 'minced steak'),
    BookIngredient.newBookIngredient(name: 'sausage'),
    BookIngredient.newBookIngredient(name: 'merguez'),
    BookIngredient.newBookIngredient(name: 'pork chop'),
    BookIngredient.newBookIngredient(name: 'ribs'),
    BookIngredient.newBookIngredient(name: 'cured ham'),
    BookIngredient.newBookIngredient(name: "pig's trotters"),
    BookIngredient.newBookIngredient(name: 'chicken'),
    BookIngredient.newBookIngredient(name: 'chicken leg'),
    BookIngredient.newBookIngredient(name: 'chicken breast'),
    BookIngredient.newBookIngredient(name: 'rabbit'),
    BookIngredient.newBookIngredient(name: 'mozzarella', unit: 'g', density: 0.95),
    BookIngredient.newBookIngredient(name: 'cheddar', unit: 'g', density: 0.95),
    BookIngredient.newBookIngredient(name: 'milk', unit: 'ml', density: 1.03),
    BookIngredient.newBookIngredient(name: 'whole milk', unit: 'ml', density: 1.03),
    BookIngredient.newBookIngredient(name: 'butter', unit: 'g', density: 0.911),
    BookIngredient.newBookIngredient(name: 'T45 flour', unit: 'g', density: 0.53),
    BookIngredient.newBookIngredient(name: 'T65 flour', unit: 'g', density: 0.53),
    BookIngredient.newBookIngredient(name: 'T80 flour', unit: 'g', density: 0.53),
    BookIngredient.newBookIngredient(name: 'T00 flour', unit: 'g', density: 0.53),
    BookIngredient.newBookIngredient(name: "baker's yeast", unit: 'g', density: 0.4),
    BookIngredient.newBookIngredient(name: 'baking powder', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'fresh yeast', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'sourdough', unit: 'g', density: 0.7),
    BookIngredient.newBookIngredient(name: 'white sugar', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'cane sugar', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'muscovado', unit: 'g', density: 0.7),
    BookIngredient.newBookIngredient(name: 'egg'),
    BookIngredient.newBookIngredient(name: 'water', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'olive oil', unit: 'ml', density: 0.92),
    BookIngredient.newBookIngredient(name: 'peanut oil', unit: 'ml', density: 0.92),
    BookIngredient.newBookIngredient(name: 'wine vinegar', unit: 'ml', density: 1.01),
    BookIngredient.newBookIngredient(name: 'balsamic vinegar', unit: 'ml', density: 1.22),
    BookIngredient.newBookIngredient(name: 'cider vinegar', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'mustard', unit: 'g', density: 1.1),
    BookIngredient.newBookIngredient(name: 'wholegrain mustard', unit: 'g', density: 1.1),
    BookIngredient.newBookIngredient(name: 'salt', unit: 'g', density: 1.2),
    BookIngredient.newBookIngredient(name: 'pepper', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'cayenne pepper', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'paprika', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'yellow curry', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'cumin', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'turmeric', unit: 'g', density: 0.7),
    BookIngredient.newBookIngredient(name: 'saffron', unit: 'g', density: 0.8),
    BookIngredient.newBookIngredient(name: 'nutmeg', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'cinnamon', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'chicken stock', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'vegetable stock', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'salad'),
    BookIngredient.newBookIngredient(name: 'rocket'),
    BookIngredient.newBookIngredient(name: 'spinach'),
    BookIngredient.newBookIngredient(name: 'chard'),
    BookIngredient.newBookIngredient(name: 'zucchini'),
    BookIngredient.newBookIngredient(name: 'eggplant'),
    BookIngredient.newBookIngredient(name: 'tomato'),
    BookIngredient.newBookIngredient(name: 'pumpkin'),
    BookIngredient.newBookIngredient(name: 'butternut'),
    BookIngredient.newBookIngredient(name: 'parsley'),
    BookIngredient.newBookIngredient(name: 'basil'),
    BookIngredient.newBookIngredient(name: 'chives'),
    BookIngredient.newBookIngredient(name: 'chervil'),
    BookIngredient.newBookIngredient(name: 'coriander'),
    BookIngredient.newBookIngredient(name: 'onion'),
    BookIngredient.newBookIngredient(name: 'red onion'),
    BookIngredient.newBookIngredient(name: 'white onion'),
    BookIngredient.newBookIngredient(name: 'shallot'),
    BookIngredient.newBookIngredient(name: 'garlic'),
    BookIngredient.newBookIngredient(name: 'dark chocolate', unit: 'g', density: 1.0),
    BookIngredient.newBookIngredient(name: 'coconut milk', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'pasta', unit: 'g', density: 0.55),
    BookIngredient.newBookIngredient(name: 'tagliatelle', unit: 'g', density: 0.55),
    BookIngredient.newBookIngredient(name: 'spaghetti', unit: 'g', density: 0.55),
    BookIngredient.newBookIngredient(name: 'basmati rice', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'arborio rice', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'Thai rice', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'walnut', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'hazelnut', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'cashew', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'peanut', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'almond', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'apple'),
    BookIngredient.newBookIngredient(name: 'pear'),
    BookIngredient.newBookIngredient(name: 'banana'),
    BookIngredient.newBookIngredient(name: 'peach'),
    BookIngredient.newBookIngredient(name: 'nectarine'),
    BookIngredient.newBookIngredient(name: 'apricot'),
    BookIngredient.newBookIngredient(name: 'cherry'),
    BookIngredient.newBookIngredient(name: 'strawberry'),
    BookIngredient.newBookIngredient(name: 'raspberry'),
    BookIngredient.newBookIngredient(name: 'redcurrant'),
    BookIngredient.newBookIngredient(name: 'blackcurrant'),
    BookIngredient.newBookIngredient(name: 'blueberry'),
    BookIngredient.newBookIngredient(name: 'blackberry'),
    BookIngredient.newBookIngredient(name: 'orange'),
    BookIngredient.newBookIngredient(name: 'clementine'),
    BookIngredient.newBookIngredient(name: 'lemon'),
    BookIngredient.newBookIngredient(name: 'grapefruit'),
    BookIngredient.newBookIngredient(name: 'lemon peel'),
    BookIngredient.newBookIngredient(name: 'rum planter', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'amber rum', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'whisky', unit: 'ml', density: 0.94),
    BookIngredient.newBookIngredient(name: 'bourbon', unit: 'ml', density: 0.94),
    BookIngredient.newBookIngredient(name: 'beer', unit: 'ml', density: 0.99),
    BookIngredient.newBookIngredient(name: 'amber beer', unit: 'ml', density: 0.99),
    BookIngredient.newBookIngredient(name: 'cider', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'calvados', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'cognac', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'champagne', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'red wine', unit: 'ml', density: 0.99),
    BookIngredient.newBookIngredient(name: 'white wine', unit: 'ml', density: 0.99),
  ],
  'fr': [
    BookIngredient.newBookIngredient(name: 'côte de boeuf'),
    BookIngredient.newBookIngredient(name: 'entrecôte'),
    BookIngredient.newBookIngredient(name: 'côte de veau'),
    BookIngredient.newBookIngredient(name: 'beefsteak'),
    BookIngredient.newBookIngredient(name: 'steak haché'),
    BookIngredient.newBookIngredient(name: 'chipolata'),
    BookIngredient.newBookIngredient(name: 'merguez'),
    BookIngredient.newBookIngredient(name: 'saucisse de Montbéliard'),
    BookIngredient.newBookIngredient(name: 'saucisse de Morteau'),
    BookIngredient.newBookIngredient(name: 'côte de porc'),
    BookIngredient.newBookIngredient(name: 'travers de porc'),
    BookIngredient.newBookIngredient(name: 'tranche de lard'),
    BookIngredient.newBookIngredient(name: 'lardons'),
    BookIngredient.newBookIngredient(name: 'jambon cru'),
    BookIngredient.newBookIngredient(name: 'jambon blanc'),
    BookIngredient.newBookIngredient(name: 'speck'),
    BookIngredient.newBookIngredient(name: 'mortadelle'),
    BookIngredient.newBookIngredient(name: 'coppa'),
    BookIngredient.newBookIngredient(name: 'bacon'),
    BookIngredient.newBookIngredient(name: 'pied de porc'),
    BookIngredient.newBookIngredient(name: 'poulet'),
    BookIngredient.newBookIngredient(name: 'cuisse de poulet'),
    BookIngredient.newBookIngredient(name: 'blanc de poulet'),
    BookIngredient.newBookIngredient(name: 'lapin'),
    BookIngredient.newBookIngredient(name: 'mozzarella', unit: 'g', density: 0.95),
    BookIngredient.newBookIngredient(name: 'comté rapé', unit: 'g', density: 0.95),
    BookIngredient.newBookIngredient(name: 'parmesan', unit: 'g', density: 0.95),
    BookIngredient.newBookIngredient(name: 'crème fraiche', unit: 'ml', density: 0.96),
    BookIngredient.newBookIngredient(name: 'lait', unit: 'ml', density: 1.03),
    BookIngredient.newBookIngredient(name: 'lait entier', unit: 'ml', density: 1.03),
    BookIngredient.newBookIngredient(name: 'beurre', unit: 'g', density: 0.911),
    BookIngredient.newBookIngredient(name: 'farine T45', unit: 'g', density: 0.53),
    BookIngredient.newBookIngredient(name: 'farine T65', unit: 'g', density: 0.53),
    BookIngredient.newBookIngredient(name: 'farine T80', unit: 'g', density: 0.53),
    BookIngredient.newBookIngredient(name: 'farine T00', unit: 'g', density: 0.53),
    BookIngredient.newBookIngredient(name: 'levure de boulanger', unit: 'g', density: 0.4),
    BookIngredient.newBookIngredient(name: 'levure chimique', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'levure fraiche', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'levain', unit: 'g', density: 0.7),
    BookIngredient.newBookIngredient(name: 'sucre blanc', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'sucre de canne', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'muscovado', unit: 'g', density: 0.7),
    BookIngredient.newBookIngredient(name: 'oeuf'),
    BookIngredient.newBookIngredient(name: "blanc d'oeuf"),
    BookIngredient.newBookIngredient(name: "jaune d'oeuf"),
    BookIngredient.newBookIngredient(name: 'eau', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'huile d\'olive', unit: 'ml', density: 0.92),
    BookIngredient.newBookIngredient(name: 'huile d\'arachide', unit: 'ml', density: 0.92),
    BookIngredient.newBookIngredient(name: 'vinaigre de vin', unit: 'ml', density: 1.01),
    BookIngredient.newBookIngredient(name: 'vinaigre balsamique', unit: 'ml', density: 1.22),
    BookIngredient.newBookIngredient(name: 'vinaigre de cidre', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'moutarde', unit: 'g', density: 1.1),
    BookIngredient.newBookIngredient(name: 'moutarde à l\'ancienne', unit: 'g', density: 1.1),
    BookIngredient.newBookIngredient(name: 'sel', unit: 'g', density: 1.2),
    BookIngredient.newBookIngredient(name: 'poivre', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'piment de Cayenne', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'piment oiseau', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'piment d\'Espelette', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'paprika', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'curry jaune', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'cumin', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'curcuma', unit: 'g', density: 0.7),
    BookIngredient.newBookIngredient(name: 'safran', unit: 'g', density: 0.8),
    BookIngredient.newBookIngredient(name: 'noix de muscade', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'cannelle', unit: 'g', density: 0.5),
    BookIngredient.newBookIngredient(name: 'fond de volaille', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'bouillon de légume', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'salade'),
    BookIngredient.newBookIngredient(name: 'roquette'),
    BookIngredient.newBookIngredient(name: 'épinard'),
    BookIngredient.newBookIngredient(name: 'blette'),
    BookIngredient.newBookIngredient(name: 'courgette'),
    BookIngredient.newBookIngredient(name: 'aubergine'),
    BookIngredient.newBookIngredient(name: 'tomate'),
    BookIngredient.newBookIngredient(name: 'carotte'),
    BookIngredient.newBookIngredient(name: 'poireau'),
    BookIngredient.newBookIngredient(name: 'pomme de terre'),
    BookIngredient.newBookIngredient(name: 'navet'),
    BookIngredient.newBookIngredient(name: 'panais'),
    BookIngredient.newBookIngredient(name: 'endive'),
    BookIngredient.newBookIngredient(name: 'céleri branche'),
    BookIngredient.newBookIngredient(name: 'potiron'),
    BookIngredient.newBookIngredient(name: 'potimarron'),
    BookIngredient.newBookIngredient(name: 'butternut'),
    BookIngredient.newBookIngredient(name: 'persil'),
    BookIngredient.newBookIngredient(name: 'basilic'),
    BookIngredient.newBookIngredient(name: 'ciboulette'),
    BookIngredient.newBookIngredient(name: 'cerfeuil'),
    BookIngredient.newBookIngredient(name: 'coriandre'),
    BookIngredient.newBookIngredient(name: 'oignon'),
    BookIngredient.newBookIngredient(name: 'oignon rouge'),
    BookIngredient.newBookIngredient(name: 'oignon blanc'),
    BookIngredient.newBookIngredient(name: 'échalotte'),
    BookIngredient.newBookIngredient(name: 'ail'),
    BookIngredient.newBookIngredient(name: 'chocolat noir', unit: 'g', density: 1.0),
    BookIngredient.newBookIngredient(name: 'lait de coco', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'pâtes', unit: 'g'),
    BookIngredient.newBookIngredient(name: 'tagliatelles', unit: 'g'),
    BookIngredient.newBookIngredient(name: 'spaghetti', unit: 'g'),
    BookIngredient.newBookIngredient(name: 'riz basmati', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'riz de camargue', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'riz arborio', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'riz thaï', unit: 'g', density: 0.85),
    BookIngredient.newBookIngredient(name: 'noix', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'noisette', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'noix de cajou', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'cacahuète', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'amande', unit: 'g', density: 0.6),
    BookIngredient.newBookIngredient(name: 'pomme'),
    BookIngredient.newBookIngredient(name: 'poire'),
    BookIngredient.newBookIngredient(name: 'banane'),
    BookIngredient.newBookIngredient(name: 'pêche'),
    BookIngredient.newBookIngredient(name: 'brugnon'),
    BookIngredient.newBookIngredient(name: 'nectarine'),
    BookIngredient.newBookIngredient(name: 'abricot'),
    BookIngredient.newBookIngredient(name: 'cerise'),
    BookIngredient.newBookIngredient(name: 'fraise'),
    BookIngredient.newBookIngredient(name: 'framboise'),
    BookIngredient.newBookIngredient(name: 'groseille'),
    BookIngredient.newBookIngredient(name: 'cassis'),
    BookIngredient.newBookIngredient(name: 'myrtille'),
    BookIngredient.newBookIngredient(name: 'mûre'),
    BookIngredient.newBookIngredient(name: 'orange'),
    BookIngredient.newBookIngredient(name: 'clémentine'),
    BookIngredient.newBookIngredient(name: 'citron'),
    BookIngredient.newBookIngredient(name: 'pamplemousse'),
    BookIngredient.newBookIngredient(name: 'zeste de citron'),
    BookIngredient.newBookIngredient(name: 'rhum planteur', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'rhum ambré', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'whisky', unit: 'ml', density: 0.94),
    BookIngredient.newBookIngredient(name: 'bourbon', unit: 'ml', density: 0.94),
    BookIngredient.newBookIngredient(name: 'bière', unit: 'ml', density: 0.99),
    BookIngredient.newBookIngredient(name: 'bière ambrée', unit: 'ml', density: 0.99),
    BookIngredient.newBookIngredient(name: 'cidre', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'calvados', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'cognac', unit: 'ml', density: 0.95),
    BookIngredient.newBookIngredient(name: 'champagne', unit: 'ml', density: 1.0),
    BookIngredient.newBookIngredient(name: 'vin rouge', unit: 'ml', density: 0.99),
    BookIngredient.newBookIngredient(name: 'vin blanc', unit: 'ml', density: 0.99),
  ]
};

// Recipe defaultRecipe = Recipe(
//   name: S.current.new_recipe_name,
//   preparationTime: 0,
//   cookingTime: 0,
//   waitingTime: 0,
//   tags: [],
//   persons: 2,
//   recipeIngredients: [],
//   steps: [RecipeStep(step: S.current.new_recipe_step)],
//   creationDate: DateTime.now().toUtc()
// );

// Recipe tutorialRecipe = Recipe(
//   name: S.current.tutorial_recipe_name,
//   preparationTime: 15,
//   cookingTime: 120,
//   waitingTime: 0,
//   tags: [S.current.tutorial_recipe_tag1, S.current.tutorial_recipe_tag2, S.current.tutorial_recipe_tag3],
//   persons: 6,
//   recipeIngredients: [
//     Ingredient(name: "Poule", quantity: 1, unit: "none"),
//     Ingredient(name: "Poireau", quantity: 4, unit: "none"),
//     Ingredient(name: "Carotte", quantity: 8, unit: "none"),
//     Ingredient(name: "Navet", quantity: 8, unit: "none"),
//     Ingredient(name: "Oignon", quantity: 1, unit: "none"),
//     Ingredient(name: "Bouquet garni", quantity: 1, unit: "none"),
//     Ingredient(name: "Brin de persil", quantity: 6, unit: "none"),
//     Ingredient(name: "Clous de girofle", quantity: 3, unit: "none"),
//     Ingredient(name: "Eau", quantity: 1.5, unit: "L"),
//   ],
//   steps: [
//     RecipeStep(step: S.current.tutorial_recipe_step1),
//     RecipeStep(step: S.current.tutorial_recipe_step2),
//     RecipeStep(step: S.current.tutorial_recipe_step3),
//   ],
//   creationDate: DateTime.now().toUtc()
// );